// features/users/hooks/useResetUserPassword.js
// =====================================================================
// Mutation: PATCH /api/users/:id/password. Returns the temporary
// password generated by the backend; the caller shows it to the admin
// so they can hand it to the user.
// =====================================================================

import { useMutation } from "@tanstack/react-query";
import { userApi } from "../../../api/userApi";

export function useResetUserPassword() {
    return useMutation({
        mutationFn: ({ id, newPassword }) =>
            userApi.resetPassword(id, newPassword),
    });
}
