const pool = require("../config/db");
const bcrypt = require("bcrypt");
const generatePassword = require("../utils/generatePassword");

const {
    validateFullName,
    validateEmail,
    validatePassword,
    validateOptionalString,
    validateRole
} = require("../utils/validation");


// Create User (Admin Only)
//
// Password handling:
//   * `password` is OPTIONAL in the request body.
//   * If provided (and not empty): validated against the regular
//     password rules (min length 8, max 255), then bcrypt-hashed and
//     stored.
//   * If absent or empty: a cryptographically secure temporary password
//     is auto-generated via the existing `generatePassword()` utility,
//     bcrypt-hashed, and stored. The plaintext temporary password is
//     returned to the caller in the 201 response so the admin can
//     communicate it to the new user. **It is never persisted in
//     plaintext and never returned by any other endpoint.**
//
// In both cases `must_change_password` is set TRUE so the new user is
// forced to pick their own password on first login.
const createUser = async (req, res) => {
    try {
        const { fullName, email, password, role } = req.body;

        const nameResult = validateFullName(fullName);
        if (!nameResult.ok) {
            return res.status(400).json({
                success: false,
                message: nameResult.message
            });
        }

        const emailResult = validateEmail(email);
        if (!emailResult.ok) {
            return res.status(400).json({
                success: false,
                message: emailResult.message
            });
        }

        // Optional string — treats undefined / null as "no password".
        const optPassword = validateOptionalString(password, "password");
        if (!optPassword.ok) {
            return res.status(400).json({
                success: false,
                message: optPassword.message
            });
        }

        let rawPassword = optPassword.value;
        let autoGenerated = false;

        if (rawPassword === undefined || rawPassword === null || rawPassword === "") {
            rawPassword = generatePassword();
            autoGenerated = true;
        } else {
            // Validate against the password rules when the admin supplies one.
            const passResult = validatePassword(rawPassword);
            if (!passResult.ok) {
                return res.status(400).json({
                    success: false,
                    message: passResult.message
                });
            }
            rawPassword = passResult.value;
        }

        const roleResult = validateRole(role);
        if (!roleResult.ok) {
            return res.status(400).json({
                success: false,
                message: roleResult.message
            });
        }

        // Check existing email
        const existingUser = await pool.query(
            "SELECT id FROM users WHERE email = $1",
            [emailResult.value]
        );

        if (existingUser.rows.length > 0) {
            return res.status(409).json({
                success: false,
                message: "Email already exists"
            });
        }

        // Hash password
        const hashedPassword = await bcrypt.hash(rawPassword, 10);

        // Insert user
        const result = await pool.query(
            `INSERT INTO users
            (
                full_name,
                email,
                password,
                role,
                must_change_password,
                is_active,
                created_at,
                updated_at
            )
            VALUES
            (
                $1,
                $2,
                $3,
                $4,
                TRUE,
                TRUE,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            )
            RETURNING
            id,
                full_name,
                email,
                role,
                must_change_password,
                is_active`,
            [
                nameResult.value,
                emailResult.value,
                hashedPassword,
                roleResult.value
            ]
        );

        const responseBody = {
            success: true,
            message: "User created successfully",
            user: result.rows[0]
        };

        // Only expose the plaintext password when we generated it; never
        // echo back what the admin just sent in plain text.
        if (autoGenerated) {
            responseBody.temporaryPassword = rawPassword;
        }

        res.status(201).json(responseBody);

    } catch (error) {
        console.error(error);

        res.status(500).json({
            success: false,
            message: "Server Error"
        });
    }


};


module.exports = {
    createUser
};